# Generated by Django 4.2.7 on 2023-12-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_tags_article_old_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='old_tags',
            field=models.ManyToManyField(blank=True, related_name='old_articles', through='webapp.ArticleTag', to='webapp.tag', verbose_name='Теги'),
        ),
    ]
