# Generated by Django 4.2.7 on 2023-12-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20231213_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='old_tags',
        ),
    ]
