# Generated by Django 4.2.7 on 2023-12-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_article_old_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
